CREATE TABLE TBL_FILME (
    ID_FILME            BIGINT          IDENTITY(1, 1) NOT NULL,
    TX_NOME             VARCHAR(255)    NULL,
    NR_DURACAO          INT             NULL,
    TP_CATEGORIA        VARCHAR(50)     NULL,  /* CategoriaFilmeEnum */
    TP_CLASSIFICACAO    VARCHAR(50)     NULL,  /* ClassificacaoIndicativaEnum */
    NR_ANO              INT             NULL,
    TX_CAPA             VARCHAR(255)    NULL,
    TX_DIRETOR          VARCHAR(255)    NULL,
    TX_ELENCO           VARCHAR(255)    NULL,
    TX_DESCRICAO        VARCHAR(255)    NULL,
    NR_AVALIACAO        FLOAT           NULL,
    CHK_EM_CARTAZ       VARCHAR(10)     NULL,  /* SimNaoEnum: S, N */
    DT_EXCLUSAO         DATETIME2(6)    NULL,
    CONSTRAINT PK_TBL_FILME PRIMARY KEY (ID_FILME)
);

CREATE TABLE TBL_SALA (
    ID_SALA             BIGINT          IDENTITY(1, 1) NOT NULL,
    TX_NOME             VARCHAR(255)    NULL,
    NR_PRECO            FLOAT           NULL,
    DT_EXCLUSAO         DATETIME2(6)    NULL,
    CONSTRAINT PK_TBL_SALA PRIMARY KEY (ID_SALA)
);

CREATE TABLE TBL_LUGAR (
    ID_LUGAR            BIGINT          IDENTITY(1, 1) NOT NULL,
    TX_FILEIRA          VARCHAR(255)    NULL,
    NR_POSICAO          INT             NULL,
    ID_SALA             BIGINT          NOT NULL,
    CONSTRAINT PK_TBL_LUGAR PRIMARY KEY (ID_LUGAR),
    CONSTRAINT FK_TBL_LUGAR_TBL_SALA FOREIGN KEY (ID_SALA)
        REFERENCES TBL_SALA (ID_SALA)
);

CREATE TABLE TBL_SESSAO (
    ID_SESSAO           BIGINT          IDENTITY(1, 1) NOT NULL,
    DT_DATA             DATETIME2(6)    NULL,
    NR_PRECO            FLOAT           NULL,
    ID_SALA             BIGINT          NOT NULL,
    ID_FILME            BIGINT          NOT NULL,
    DT_EXCLUSAO         DATETIME2(6)    NULL,
    CONSTRAINT PK_TBL_SESSAO PRIMARY KEY (ID_SESSAO),
    CONSTRAINT FK_TBL_SESSAO_TBL_SALA FOREIGN KEY (ID_SALA)
        REFERENCES TBL_SALA (ID_SALA),
    CONSTRAINT FK_TBL_SESSAO_TBL_FILME FOREIGN KEY (ID_FILME)
        REFERENCES TBL_FILME (ID_FILME)
);

CREATE TABLE TBL_INGRESSO (
    ID_INGRESSO         BIGINT          IDENTITY(1, 1) NOT NULL,
    TP_INGRESSO         VARCHAR(50)     NULL,  /* TipoIngressoEnum */
    NR_PRECO            FLOAT           NULL,
    ID_SESSAO           BIGINT          NULL,
    ID_LUGAR            BIGINT          NULL,
    CONSTRAINT PK_TBL_INGRESSO PRIMARY KEY (ID_INGRESSO),
    CONSTRAINT FK_TBL_INGRESSO_TBL_SESSAO FOREIGN KEY (ID_SESSAO)
        REFERENCES TBL_SESSAO (ID_SESSAO),
    CONSTRAINT FK_TBL_INGRESSO_TBL_LUGAR FOREIGN KEY (ID_LUGAR)
        REFERENCES TBL_LUGAR (ID_LUGAR)
);

CREATE TABLE TBL_PEDIDO (
    ID_PEDIDO           BIGINT          IDENTITY(1, 1) NOT NULL,
    TX_NUMERO           VARCHAR(255)    NULL,
    DT_CRIACAO          DATETIME2(6)    NULL,
    TP_STATUS           VARCHAR(50)     NULL,  /* StatusPedidoEnum */
    CONSTRAINT PK_TBL_PEDIDO PRIMARY KEY (ID_PEDIDO)
);

CREATE TABLE TBL_PAGAMENTO (
    ID_PAGAMENTO        BIGINT          IDENTITY(1, 1) NOT NULL,
    NR_VALOR            FLOAT           NULL,
    TP_STATUS           VARCHAR(50)     NULL,  /* StatusPagamentoEnum */
    ID_PEDIDO           BIGINT          NOT NULL,
    CONSTRAINT PK_TBL_PAGAMENTO PRIMARY KEY (ID_PAGAMENTO),
    CONSTRAINT UQ_TBL_PAGAMENTO_ID_PEDIDO UNIQUE (ID_PEDIDO),
    CONSTRAINT FK_TBL_PAGAMENTO_TBL_PEDIDO FOREIGN KEY (ID_PEDIDO)
        REFERENCES TBL_PEDIDO (ID_PEDIDO)
);

CREATE TABLE TBL_DADOS_PAGAMENTO (
    ID_DADOS_PAGAMENTO  BIGINT          IDENTITY(1, 1) NOT NULL,
    TX_NOME             VARCHAR(255)    NULL,
    TX_EMAIL            VARCHAR(255)    NULL,
    TX_NUMERO           VARCHAR(255)    NULL,
    TX_EXPIRACAO        VARCHAR(255)    NULL,
    TX_BANDEIRA         VARCHAR(255)    NULL,
    TX_CODIGO           VARCHAR(255)    NULL,
    NR_PARCELAS         INT             NULL,
    NR_VALOR            FLOAT           NULL,
    TP_TIPO             VARCHAR(50)     NULL,  /* TipoFormaPagamentoEnum */
    ID_PAGAMENTO        BIGINT          NOT NULL,
    CONSTRAINT PK_TBL_DADOS_PAGAMENTO PRIMARY KEY (ID_DADOS_PAGAMENTO),
    CONSTRAINT UQ_TBL_DADOS_PAGAMENTO_ID_PAGAMENTO UNIQUE (ID_PAGAMENTO),
    CONSTRAINT FK_TBL_DADOS_PAGAMENTO_TBL_PAGAMENTO FOREIGN KEY (ID_PAGAMENTO)
        REFERENCES TBL_PAGAMENTO (ID_PAGAMENTO)
);

CREATE TABLE TBL_REL_PEDIDO_INGRESSO (
    ID_PEDIDO           BIGINT          NOT NULL,
    ID_INGRESSO         BIGINT          NOT NULL,
    CONSTRAINT PK_TBL_REL_PEDIDO_INGRESSO PRIMARY KEY (ID_PEDIDO, ID_INGRESSO),
    CONSTRAINT FK_TBL_REL_PEDIDO_INGRESSO_PEDIDO FOREIGN KEY (ID_PEDIDO)
        REFERENCES TBL_PEDIDO (ID_PEDIDO),
    CONSTRAINT FK_TBL_REL_PEDIDO_INGRESSO_INGRESSO FOREIGN KEY (ID_INGRESSO)
        REFERENCES TBL_INGRESSO (ID_INGRESSO)
);